### ISSUE TITLE
Use strings for labels

### ISSUE THREAD

**Issue by stephanepechard** [MatthiasRobbers/shortbread#1]
Hi,

For icons, I can use project's like `R.drawable.ic_shortcut_movies`, but labels are hardcoded strings. How can I use project's strings like `R.string.title`?
Thanks for the lib!

**Comment by MatthiasRobbers** [comment]
Hi,

sorry that was just missing in the docs. There is `shortLabelRes`, `longLabelRes` and `disabledMessageRes`. Added with #2.

Thanks!
