### ISSUE TITLE
Error:(8, 26) error: cannot find symbol class ShortcutInfo

### ISSUE THREAD

**Issue by JP1016** [MatthiasRobbers/shortbread#11]
package shortbread;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.TaskStackBuilder;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ShortcutInfo;
import android.graphics.drawable.Icon;
import com.devzapps.irctcquicktatkalbooking.Activity.TicketViewer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@SuppressLint({
        "NewApi",
        "ResourceType"
})
public final class ShortbreadGenerated {
    public static List<List<ShortcutInfo>> createShortcuts(Context context) {
        List<ShortcutInfo> enabledShortcuts = new ArrayList<>();
        List<ShortcutInfo> disabledShortcuts = new ArrayList<>();
        enabledShortcuts.add(new ShortcutInfo.Builder(context, "ticket_list")
                .setShortLabel("My Tickets")
                .setIcon(Icon.createWithResource(context, 2130837744))
                .setIntents(TaskStackBuilder.create(context)
                        .addParentStack(TicketViewer.class)
                        .addNextIntent(new Intent(context, TicketViewer.class)
                                .setAction(Intent.ACTION_VIEW))
                        .getIntents())
                .setRank(0)
                .build());
        return Arrays.asList(enabledShortcuts, disabledShortcuts);
    }

    public static void callMethodShortcut(Activity activity) {
    }
}

Error on ShortBreadGenerated.java

**Comment by MatthiasRobbers** [comment]
Make sure that your `compileSdkVersion` and `targetSdkVersion` are at least `25`. App shortcuts is an Android 7.1 feature.

**Comment by JP1016** [comment]
Sorry!! My mistake
