### ISSUE TITLE
Multiple shortcuts in same Activity

### ISSUE THREAD

**Issue by THMCombine** [MatthiasRobbers/shortbread#19]
Hello,

First of all, it's a very lovely library.
My application is very fragment heavy, and I wish to add multiple @Shortcut to the same activity. Is this possible in the current iteration?
Or could it be solved using the @Repeatable annotation? http://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

**Comment by MatthiasRobbers** [comment]
This should be no problem with version 1.0.2. You just need one Shortcut annotation per method. So for example you can use one public method show fragment A and another public method to show fragment B.

**Comment by THMCombine** [comment]
Right, not sure why I had gotten the idea that it was only for annotating Classes. Thanks a lot for the quick answer.
