### ISSUE TITLE
Is there a method call back when a shortcut is received by an activity?

### ISSUE THREAD

**Issue by Akshshr** [MatthiasRobbers/shortbread#23]
Hey! 

Is there/there should be a method that gets a call back declared in the activity in case one wants to further handle intent from the shortcut, so you can post process that from the call back method.

Would be really cool! 

**For example:**

_public onShortcutCalled(String shortcutId){
if(shortcutId == "profile"){
  //Open profile
  }
 if(shortcutId == "cats"){
   //Open cats
  }
}_

**Comment by MatthiasRobbers** [comment]
Hey! It should be possible but actually that is exactly what the method annotations are for.

    @Shortcut(id = "profile")
    public openProfile() {
        // Open profile
    }

    @Shortcut(id = "cats")
    public openCats() {
        // Open cats
    }
