### ISSUE TITLE
Support for Kotlin

### ISSUE THREAD

**Issue by maskaravivek** [MatthiasRobbers/shortbread#25]
As of now, the library doesn't work properly in Kotlin. It gives the following error

```
An annotation argument should be compile-time constant. 
```

This is the code that i am using. 

```
@Shortcut(id = "mastered", icon =  R.drawable.favorites, shortLabelRes = R.string.mastered_category)
```

The above error comes both for drawable and string resources.

**Comment by lmj0011** [comment]
repo is dead

**Comment by lmj0011** [comment]
Shortbread should work with Kotlin.
Make sure you're adding it into your app's `build.gradle` file like this:

```gradle
apply plugin: 'kotlin-kapt'

dependencies {
  ...
  implementation 'com.github.matthiasrobbers:shortbread:1.0.2'
  kapt 'com.github.matthiasrobbers:shortbread-compiler:1.0.2'
}
```
making use of the `kotlin-kapt` [plugin ](https://kotlinlang.org/docs/reference/kapt.html) is key here.

see this stackoverflow [answer](https://stackoverflow.com/a/47617092/2445763)

**Comment by MatthiasRobbers** [comment]
As @lmj0011 mentioned, it works with Kotlin. The issue's annotation works in version 1.0.2 and 1.1.0.
