### ISSUE TITLE
Getting java.lang.ClassNotFoundException while trying to init the library

### ISSUE THREAD

**Issue by cre8ivejp** [MatthiasRobbers/shortbread#5]
I'm getting this exception when I call `Shortbread.create(this);` in my Application class.
Am I missing something?

OS: 7.1
Device: Google Pixel

```
java.lang.ClassNotFoundException: shortbread.ShortbreadGenerated
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:400)
W/System.err:     at java.lang.Class.forName(Class.java:326)
W/System.err:     at shortbread.Shortbread.create(Shortbread.java:37)
Caused by: java.lang.ClassNotFoundException: Didn't find class "shortbread.ShortbreadGenerated"
```

**Comment by MatthiasRobbers** [comment]
The code generation did not complete. Hard to tell what the exact issue is. Did you add any `Shortcut` annotations yet? Can post the elements and the shortcuts so I can try to reproduce? Or even better, point me to a sample project with that I can reproduce it. Thanks!

**Comment by gargas** [comment]
I am also getting the same error

**Comment by MatthiasRobbers** [comment]
@gargas I tried to reproduce but the only state where I get the `ClassNotFoundException` is when I have zero `@Shortcut` annotations in my code. That is a bug and I will fix it but that is probably not the case here, right?

Also are you using other annotation processors that are not using the `annotationProcessor` notation in gradle? Are you using proguard?

**Comment by gargas** [comment]
I had added @Shortcut annotation in several activities.  yes i am using proguard

**Comment by MatthiasRobbers** [comment]
Just checked again, it works with proguard. 

I want to fix this but I need to reproduce it. Can you post your `build.gradle` by any chance? Is there anything special with your project like using an old version of the Android Gradle Plugin or something? As written before, a sample project would be the best.

**Comment by dlackty** [comment]
Same problem here even without proguard. Trying to figure out what happened.

**Comment by AlexanderThiele** [comment]
I had the same problem. 

In my project we're using a different annotation processor plugin:
`apply plugin: 'com.neenbedankt.android-apt'`

And i fixed this crash by using ```apt``` instead of ```annotationProcessor```:

`compile 'com.github.matthiasrobbers:shortbread:1.0.0'`
`apt 'com.github.matthiasrobbers:shortbread-compiler:1.0.0'`

**Comment by MatthiasRobbers** [comment]
Thanks, @AlexanderThiele!

So the solution is to either use the old `apt` as a workaround

```groovy
compile 'com.github.matthiasrobbers:shortbread:1.0.0'
apt 'com.github.matthiasrobbers:shortbread-compiler:1.0.0'
```

or better, migrate your project to the new built-in `annotationProcessor` syntax. 
Migration guide: [https://bitbucket.org/hvisser/android-apt/wiki/Migration](https://bitbucket.org/hvisser/android-apt/wiki/Migration)
